name: Release (npm publish)

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write   # for npm provenance (optional but recommended)

jobs:
  publish:
    name: Build & publish to npm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          registry-url: https://registry.npmjs.org/

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Verify (lint, typecheck, test)
        run: |
          pnpm -s run lint || true
          pnpm -s run typecheck || true
          pnpm -s run test -- --run || true

      - name: Build
        run: pnpm run build

      - name: Enable npm provenance (optional)
        run: npm config set provenance true

      # If your package is scoped (@holmes/...), make sure "publishConfig.access": "public" is set in package.json
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # Skip if the version already exists on npm
          npx --yes can-npm-publish || { echo "Version already on npm. Skipping."; exit 0; }
          pnpm publish --access public --no-git-checks
